### ISSUE TITLE
Suggestion: mount optimized icons

### ISSUE THREAD

**Issue by rhcarvalho** [gohugoio/hugo-mod-heroicons#5]
I was looking at what gets published to NPM, and seems that their build script takes input from `src` and output to `optimize`, then copying the result to top-level directories and [releasing that](https://www.npmjs.com/package/heroicons?activeTab=code).

 https://github.com/tailwindlabs/heroicons/blob/eee05eb77af6cdedfb97f128d1998773fc984b28/package.json#L17-L19

In my project I changed the mount point to use the optimized version of the icons:

```toml
  [[module.imports]]
    path="github.com/tailwindlabs/heroicons"
  [[module.imports.mounts]]
    source = "optimized"
    target = "assets/svg/heroicons"
```

Among other benefits, this allows for easier control of icon size using CSS. Example:

```html
{{ $icon := resources.Get "svg/heroicons/20/solid/phone.svg" }}
<span class="w-8 h-auto">{{ $icon.Content | safeHTML }}</span>
```
